name = "HarmonicPowerModels"
uuid = "56365af1-a032-4c1d-861b-3c9f15bdb54e"
authors = ["Frederik Geth", "Tom Van Acker"]
version = "0.1.0"

[deps]
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
ElectricalEngineering = "84e62fa8-74a0-5990-9214-c45bd74ae4d7"
InfrastructureModels = "2030c09a-7f63-5d83-885d-db604e0e9cc0"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Memento = "f28f55f0-a522-5efc-85c2-fe41dfb9b2d9"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SignalDecomposition = "11a47235-7b84-4c7c-b885-fc3e2a9cf955"

[compat]
julia = "1"
PowerModels = "0.19.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
